"use client";

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Save } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { Store, ClientType, Client } from '../types';
import ClientForm from '../components/ClientForm'; // Import the new ClientForm

const MOCK_STORES: Store[] = [
  { id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef', name: 'CALDAS DA RAINHA', short_code: 'CR', address: 'Rua Principal, 10, Caldas da Rainha', phone: '262123456', email: 'caldas@gestaos.pt' },
  { id: 'f0e9d8c7-b6a5-4321-fedc-ba9876543210', name: 'PORTO DE MÓS', short_code: 'PM', address: 'Avenida Central, 20, Porto de Mós', phone: '244987654', email: 'portodemos@gestaos.pt' },
];

const NewClient: React.FC = () => {
  const navigate = useNavigate();
  const [stores, setStores] = useState<Store[]>([]);
  const [loading, setLoading] = useState(false);
  const isDemo = localStorage.getItem('demo_session') === 'true';

  const [formData, setFormData] = useState<Client>({
    id: '', // Will be generated by Supabase
    name: '',
    address: '',
    phone: '',
    email: '',
    contact_person: '',
    notes: '',
    store_id: '',
    billing_name: '',
    type: ClientType.OUTRO, // Default type
  });

  useEffect(() => {
    fetchStores();
  }, []);

  const fetchStores = async () => {
    if (isDemo) {
      setStores(MOCK_STORES);
      return;
    }
    try {
      const { data, error } = await supabase.from('stores').select('id, name, short_code').order('name');
      if (error) throw error;
      setStores(data || []);
    } catch (error) {
      console.error('Error fetching stores:', error);
      setStores(MOCK_STORES); // Fallback to mock data
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value as ClientType | string });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (!formData.name || !formData.store_id) {
        throw new Error("Por favor, preencha os campos obrigatórios: Nome do Cliente e Loja Associada.");
      }

      if (isDemo) {
        console.log("Novo Cliente (Demo):", formData);
        await new Promise(r => setTimeout(r, 1000));
        alert("Cliente adicionado com sucesso! (Modo Demo)");
        navigate('/clients');
        return;
      }

      const { error } = await supabase.from('clients').insert({
        name: formData.name,
        address: formData.address || null,
        phone: formData.phone || null,
        email: formData.email || null,
        contact_person: formData.contact_person || null,
        notes: formData.notes || null,
        store_id: formData.store_id,
        type: formData.type,
        billing_name: formData.billing_name || null,
      });

      if (error) throw error;

      alert("Cliente adicionado com sucesso!");
      navigate('/clients');
    } catch (err: any) {
      alert(err.message || "Erro ao adicionar cliente.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto">
      <div className="flex items-center mb-6">
        <button onClick={() => navigate(-1)} className="mr-4 text-gray-500 hover:text-gray-700">
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-2xl font-bold text-gray-900">Novo Cliente</h1>
      </div>

      <form onSubmit={handleSubmit}>
        <ClientForm
          formData={formData}
          handleChange={handleChange}
          stores={stores}
          loading={loading}
        />
        <div className="pt-4 flex justify-end">
          <button
            type="submit"
            disabled={loading}
            className="flex items-center justify-center bg-blue-600 text-white px-8 py-3 rounded-lg font-bold hover:bg-blue-700 shadow-md transition-all disabled:opacity-50"
          >
            <Save size={20} className="mr-2" />
            {loading ? 'A adicionar...' : 'Adicionar Cliente'}
          </button>
        </div>
      </form>
    </div>
  );
};

export default NewClient;