import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Save, ArrowLeft, Calendar, AlertTriangle, FileText } from 'lucide-react';
import { supabase } from '../supabaseClient';
import { Client, Equipment, OSType, Store, OSStatus } from '../types';

const NewServiceOrder: React.FC = () => {
  const navigate = useNavigate();
  const [clients, setClients] = useState<Client[]>([]);
  const [equipments, setEquipments] = useState<Equipment[]>([]);
  const [stores, setStores] = useState<Store[]>([]);
  const [loading, setLoading] = useState(false);

  // Form State
  const [formData, setFormData] = useState({
    store_id: '', // New field
    client_id: '',
    equipment_id: '',
    type: OSType.AVARIA,
    priority: 'media',
    description: '',
    scheduled_date: new Date().toISOString().split('T')[0] // Today YYYY-MM-DD
  });

  // Mock data for demo
  const isDemo = localStorage.getItem('demo_session') === 'true';

  const MOCK_STORES: Store[] = [
    { id: 'a1b2c3d4-e5f6-7890-1234-567890abcdef', name: 'CALDAS DA RAINHA', short_code: 'CR', address: '', phone: '', email: '' },
    { id: 'f0e9d8c7-b6a5-4321-fedc-ba9876543210', name: 'PORTO DE MÓS', short_code: 'PM', address: '', phone: '', email: '' },
  ];

  const MOCK_CLIENTS: Client[] = [
    { id: '1', name: 'Hotel Baía Azul', type: 'Hotel', address: '', phone: '', email: '', contact_person: '', store_id: MOCK_STORES[0].id },
    { id: '2', name: 'Restaurante O Pescador', type: 'Restaurante', address: '', phone: '', email: '', contact_person: '', store_id: MOCK_STORES[1].id },
    { id: '3', name: 'Pastelaria Central', type: 'Pastelaria', address: '', phone: '', email: '', contact_person: '', store_id: MOCK_STORES[0].id },
  ];

  const MOCK_EQUIPMENTS: Equipment[] = [
    { id: '1', client_id: '1', type: 'Máquina de Gelo', brand: 'Hoshizaki', model: 'IM-45', serial_number: '123', status: 'ativo', store_id: MOCK_STORES[0].id },
    { id: '2', client_id: '1', type: 'Forno', brand: 'Rational', model: 'iCombi', serial_number: '456', status: 'ativo', store_id: MOCK_STORES[0].id },
    { id: '3', client_id: '2', type: 'Grelhador', brand: 'GrelhaMox', model: 'G500', serial_number: '789', status: 'ativo', store_id: MOCK_STORES[1].id },
  ];

  useEffect(() => {
    fetchStores();
  }, []);

  useEffect(() => {
    if (formData.store_id) {
      fetchClients(formData.store_id);
    } else {
      setClients([]);
      setFormData(prev => ({ ...prev, client_id: '', equipment_id: '' }));
    }
  }, [formData.store_id]);

  // When client changes, fetch their equipment
  useEffect(() => {
    if (formData.client_id) {
      fetchEquipments(formData.client_id);
    } else {
      setEquipments([]);
      setFormData(prev => ({ ...prev, equipment_id: '' }));
    }
  }, [formData.client_id]);

  const fetchStores = async () => {
    if (isDemo) {
      setStores(MOCK_STORES);
      return;
    }
    const { data } = await supabase.from('stores').select('id, name, short_code');
    if (data) setStores(data as any);
  };

  const fetchClients = async (storeId: string) => {
    if (isDemo) {
      setClients(MOCK_CLIENTS.filter(c => c.store_id === storeId));
      return;
    }
    const { data } = await supabase.from('clients').select('id, name').eq('store_id', storeId);
    if (data) setClients(data as any);
  };

  const fetchEquipments = async (clientId: string) => {
    if (isDemo) {
      setEquipments(MOCK_EQUIPMENTS.filter(e => e.client_id === clientId));
      return;
    }
    const { data } = await supabase.from('equipments').select('*').eq('client_id', clientId);
    if (data) setEquipments(data);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (!formData.store_id || !formData.client_id || !formData.description) {
        throw new Error("Preencha os campos obrigatórios (Loja, Cliente, Descrição).");
      }

      if (isDemo) {
        // Simulate code generation for demo
        const selectedStore = MOCK_STORES.find(s => s.id === formData.store_id);
        const shortCode = selectedStore ? selectedStore.short_code : 'DEMO';
        const osDate = new Date().toISOString().split('T')[0].replace(/-/g, '');
        const mockCode = `${shortCode}-${osDate}-${Math.floor(Math.random() * 999).toString().padStart(3, '0')}`;

        console.log("OS Criada (Demo):", { ...formData, code: mockCode });
        await new Promise(r => setTimeout(r, 1000)); // Fake network delay
        alert("Ordem de Serviço criada com sucesso! (Modo Demo)");
        navigate('/os');
        return;
      }

      // The 'code' will be automatically generated by the database trigger
      const { error } = await supabase.from('service_orders').insert({
        store_id: formData.store_id, // Save store_id
        client_id: formData.client_id,
        equipment_id: formData.equipment_id || null,
        type: formData.type,
        priority: formData.priority,
        description: formData.description,
        status: OSStatus.POR_INICIAR, // Default status for new OS
        scheduled_date: formData.scheduled_date
      });

      if (error) throw error;

      navigate('/os');
    } catch (err: any) {
      alert(err.message);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  return (
    <div className="max-w-3xl mx-auto">
      <div className="flex items-center mb-6">
        <button onClick={() => navigate(-1)} className="mr-4 text-gray-500 hover:text-gray-700">
          <ArrowLeft size={24} />
        </button>
        <h1 className="text-2xl font-bold text-gray-900">Nova Ordem de Serviço</h1>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
        <form onSubmit={handleSubmit} className="p-6 md:p-8 space-y-6">
          
          {/* Loja */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Loja *</label>
            <select
              name="store_id"
              value={formData.store_id}
              onChange={handleChange}
              required
              className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5"
            >
              <option value="">Selecione uma loja</option>
              {stores.map(s => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Cliente */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Cliente *</label>
              <select
                name="client_id"
                value={formData.client_id}
                onChange={handleChange}
                required
                disabled={!formData.store_id}
                className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5 disabled:bg-gray-100 disabled:text-gray-400"
              >
                <option value="">Selecione um cliente</option>
                {clients.map(c => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>

            {/* Equipamento */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Equipamento</label>
              <select
                name="equipment_id"
                value={formData.equipment_id}
                onChange={handleChange}
                disabled={!formData.client_id}
                className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5 disabled:bg-gray-100 disabled:text-gray-400"
              >
                <option value="">Selecione o equipamento (Opcional)</option>
                {equipments.map(e => (
                  <option key={e.id} value={e.id}>{e.type} - {e.brand} ({e.model})</option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Tipo */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Tipo de Serviço</label>
              <select
                name="type"
                value={formData.type}
                onChange={handleChange}
                className="w-full border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5"
              >
                <option value="avaria">Avaria / Reparação</option>
                <option value="manutencao">Manutenção Preventiva</option>
                <option value="instalacao">Instalação</option>
                <option value="revisao">Revisão Geral</option>
              </select>
            </div>

            {/* Prioridade */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Prioridade</label>
              <div className="relative">
                <AlertTriangle className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
                <select
                  name="priority"
                  value={formData.priority}
                  onChange={handleChange}
                  className="w-full pl-10 border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5"
                >
                  <option value="baixa">Baixa</option>
                  <option value="media">Média</option>
                  <option value="alta">Alta</option>
                  <option value="urgente">Urgente</option>
                </select>
              </div>
            </div>
          </div>

          {/* Data do Pedido */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Data do Pedido</label>
            <div className="relative max-w-sm">
              <Calendar className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
              <input
                type="date"
                name="scheduled_date"
                value={formData.scheduled_date}
                onChange={handleChange}
                className="w-full pl-10 border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5"
              />
            </div>
          </div>

          {/* Descrição */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Descrição do Problema / Pedido *</label>
            <div className="relative">
              <FileText className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
              <textarea
                name="description"
                rows={4}
                required
                value={formData.description}
                onChange={handleChange}
                className="w-full pl-10 border-gray-300 rounded-lg shadow-sm focus:ring-blue-500 focus:border-blue-500 border p-2.5"
                placeholder="Descreva detalhadamente o problema reportado ou o serviço a realizar..."
              />
            </div>
          </div>

          <div className="pt-4 flex justify-end">
            <button
              type="submit"
              disabled={loading}
              className="flex items-center justify-center bg-blue-600 text-white px-8 py-3 rounded-lg font-bold hover:bg-blue-700 shadow-md transition-all disabled:opacity-50"
            >
              <Save size={20} className="mr-2" />
              {loading ? 'A criar...' : 'Criar Ordem de Serviço'}
            </button>
          </div>

        </form>
      </div>
    </div>
  );
};

export default NewServiceOrder;